### PR TITLE
Adds max height to children container

### PR DESCRIPTION
**Pull request by jdk27**
### What is this?
Connected to #47 
Adds max height to children container that lists the contents of folders and adds a permanent scrollbar to show overflow.

Screen Shot 2019-07-17 at 5 11 17 PM

### CODE REVIEW

**Comment by afischer** [comment]
Perhaps a better solution would be to maintain full heights for all boxes, reorganized the vertical positions of the boxes in a more "pinterest-y" way, allowing for multiple smaller boxes to fill the space to the sides of taller boxes?

I think this is often referred to as a "masonry" or "cascading grid," something like [this](https://codepen.io/desandro/pen/RPKgEN). 

Would love to hear some more thoughts about how to better solve #47.

**Comment by isaacwhite** [comment]
Two things worry me about the masonry approach, though it's worth considering:
- the frontend (and possibly backend) technical complexity of a client side masonry implementation seems like a big increase from what we're doing now
- my understanding is that masonry does not enforce an exact order, which we try to keep consistent generally in Library either alphabetically or by folder weight via leading number

Is there a way to use the masonry that wouldn't change the order and preserve the approach that we have now?

**Comment by jdk27** [comment]
Screen Shot 2019-07-18 at 11 24 18 AM
My concern with the "See More" button is if adjacent containers have the same number of items but different number of lines than it looks off to have that button when there is already enough space

**Comment by afischer** [comment]
> * the frontend (and possibly backend) technical complexity of a client side masonry implementation seems like a big increase from what we're doing now
> * my understanding is that masonry does not enforce an exact order, which we try to keep consistent generally in Library either alphabetically or by folder weight via leading number

Sorry — I should have been more specific! I definitely would not use the masonry JS library — we could construct a similar thing using just flexbox that would give us full control of the ordering and layout.

**Comment by isaacwhite** [comment]
@jdk27 Your screenshot demonstrates the issue with just counting the number of items very well. Is there a hybrid approach with the max height as you describe that removes the restriction for that one container (maybe via a class addition) when the "See more" button is clicked?

It seems to me the tricky part in that case would just be detecting the overflow scenario to include the button, but that if we could pull it off would provide the best of both worlds.

**Comment by jdk27** [comment]
Quick update: I've got a way to check for overflow just working on the button to change styles

**Comment by jdk27** [comment]
Here is how the see more button looks now. It appears when the children list is longer than 300 px.

Screen Shot 2019-07-22 at 10 03 45 AM Screen Shot 2019-07-22 at 10 03 55 AM

**Pull request merged**
